### ISSUE TITLE
Select bus Route

### ISSUE THREAD

**Issue by jugbeep** [chadkeeven/Project-3#74]
The buttons for selecting bus route are small. Maybe make the whole bus route field selectable or make it a button.

**Comment by jugbeep** [comment]
Make the save your route button the same size as the 'schedule' and the 'cancel all alarms' button.

**Comment by jasonbrettcox** [comment]
the button cannot be that large. it can be bigger but not that much bigger.

**Comment by jasonbrettcox** [comment]
resolved. the buttons are bigger now.
